server:
  port: 9005

spring:
  application:
    name: epiprev-admin
  config:
    import:
      - classpath:config.yml
      - classpath:rpc.yml
      - classpath:cache.yml
      - classpath:file.yml

