server:
  port: 9001
spring:
  application:
    name: business-epiprev-user
  config:
    import:
      - classpath:datasource.yml
      - classpath:cache.yml
      - classpath:config.yml
      - classpath:rpc.yml
      - classpath:file.yml