spring:
  datasource:
    url: jdbc:mysql://47.99.39.81:3306/epiprev
    username: zhangbo
    password: 2I0h2AdnMGM81fVtLw+gYA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource